Vagrant.configure("2") do |config|

    config.vm.define "lb" do |lb|
        lb.vm.box = "ubuntu/bionic64"
        lb.vm.hostname = "loadbalancer"
        lb.vm.network "private_network", ip: "192.168.5.10"
        lb.vm.provision "shell", path: "./provision-lb.sh"
    end

    config.vm.define "web1" do |web1|
        web1.vm.box = "ubuntu/bionic64"
        web1.vm.hostname = "webserver1"
        web1.vm.network "private_network", ip: "192.168.5.20"
        web1.vm.provision  "shell", path: "./provision-web.sh"
    end

    config.vm.define "web2" do |web2|
        web2.vm.box = "ubuntu/bionic64"
        web2.vm.hostname = "webserver2"
        web2.vm.network "private_network", ip: "192.168.5.30"
        web2.vm.provision  "shell", path: "./provision-web.sh"
    end


config.vbguest.auto_update = false   
config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
     end

end